name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.ACCESS_TOKEN }}
      
      - name: Install nodejs
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"

      - name: deploy to pages
        run: |
          git config --global user.email "${{secrets.EMAIL}}"
          git config --global user.name "${{secrets.NAME}}"
          git remote set-url origin https://BarsaRanjeet:${{ secrets.ACCESS_TOKEN }}@github.com/BarsaRanjeet/BarsaRanjeet.github.io.git
          sudo npm i -g yarn
          yarn
          yarn deploy
