name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:

      - name: Checkout this repo
        uses: actions/checkout@v2
 

      - name: Install nodejs
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: publish
        run: |
          npm install
          npm run deploy
